#!/usr/bin/env bash

# explicitly source any .profile that exists, because bash itself won't when this file exists
if [ -f "${HOME}"/.profile ]; then
    source "${HOME}"/.profile
fi

# source PredicTrip utility scripts
UTIL_DIR="${PREDICTRIP_HOME}"/code/util/

source "${UTIL_DIR}"/logs.bash
source "${UTIL_DIR}"/cluster.bash
