#!/usr/bin/env sh
# install as .profile and create .bash_profile that first explicitly runs this if it exists

# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
        . "$HOME/.bashrc"
    fi
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

## PredicTrip customizations:

JAVA_HOME=/usr/lib/jvm/adoptopenjdk-8-hotspot-amd64
export JAVA_HOME

if [ -d /usr/local/hadoop ]; then
    PATH=/usr/local/hadoop/bin:/usr/local/hadoop/sbin:"$PATH"
    HADOOP_HOME=/usr/local/hadoop
    export HADOOP_HOME
fi

if [ -d /usr/local/spark ]; then
    PATH=/usr/local/spark/bin:/usr/local/spark/sbin:"$PATH"
fi

if [ -d /usr/local/hbase ]; then
    PATH=/usr/local/hbase/bin:"$PATH"
    HBASE_HOME=/usr/local/hbase
    export HBASE_HOME
fi

if [ -d /usr/local/geomesa-hbase ]; then
    PATH=/usr/local/geomesa-hbase/bin:"$PATH"
fi

if [ -d /usr/local/geoserver ]; then
    PATH=/usr/local/geoserver/bin:"$PATH"
    GEOSERVER_HOME=/usr/local/geoserver
    export GEOSERVER_HOME
fi

export PATH
