#!/usr/bin/env sh
# install as .profile and ensure that any .bash_profile that exists explicitly runs this, because bash itself won't if
# .bash_profile exists

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
        . "$HOME/.bashrc"
    fi
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

## PredicTrip customizations:

JAVA_HOME=/usr/lib/jvm/adoptopenjdk-8-hotspot-amd64
export JAVA_HOME

PREDICTRIP_HOME="$HOME"/predictrip
export PREDICTRIP_HOME

if [ -d /usr/local/hadoop ]; then
    HADOOP_HOME=/usr/local/hadoop
    export HADOOP_HOME
    PATH="$HADOOP_HOME"/bin:"$HADOOP_HOME"/sbin:"$PATH"
    YARN_CONF_DIR=$HADOOP_HOME/etc/hadoop/
    export YARN_CONF_DIR
fi

if [ -d /usr/local/spark ]; then
    SPARK_HOME=/usr/local/spark
    export SPARK_HOME
    PATH="$SPARK_HOME"/bin:"$SPARK_HOME"/sbin:"$PATH"
    PYSPARK_PYTHON=python3
    export PYSPARK_PYTHON
fi

if [ -d /usr/local/hbase ]; then
    HBASE_HOME=/usr/local/hbase
    export HBASE_HOME
    PATH="$HBASE_HOME"/bin:"$PATH"
fi

if [ -d /usr/local/geomesa-hbase ]; then
    GEOMESA_HBASE_HOME=/usr/local/geomesa-hbase
    export GEOMESA_HBASE_HOME
    PATH="$GEOMESA_HBASE_HOME"/bin:"$PATH"
fi

if [ -d /usr/local/geoserver ]; then
    GEOSERVER_HOME=/usr/local/geoserver
    export GEOSERVER_HOME
    GEOSERVER_DATA_DIR=/var/local/geoserver
    export GEOSERVER_DATA_DIR
    PATH="$GEOSERVER_HOME"/bin:"$PATH"
fi

export PATH
